server {
    listen 80;
    server_name 51.250.20.108;

    location /static/ {
        alias /home/deploy/m2bilingual/staticfiles/;
        expires 30d;
    }

    location /media/ {
        alias /home/deploy/m2bilingual/media/;
        expires 30d;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/deploy/m2bilingual/lms.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    client_max_body_size 20M;
}
