[project]
name = "djangodrf"
version = "0.1.0"
description = ""
authors = [
    {name = "iuliia",email = "zohn12333@gmail.com"}
]
requires-python = "^3.14"
[tool.poetry.dependencies]
Django = "4.2.7"
django-filter = "23.3"
django-celery-beat = "2.5.0"
django-celery-results = "2.5.1"
drf-spectacular = "0.27.0"
celery-types = "^0.26.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
